import { APP_VERSION, BUILD_DATE } from "./constants.js";
import { createDashboard, normalizeDashboard } from "./dashboard.js";
import { deepClone, nowIso, uid } from "./utils.js";

export function exportDashboardPackage(workspace, dashboardId) {
  const dashboard = workspace.dashboards.find((item) => item.id === dashboardId);
  if (!dashboard) throw new Error("Dashboard not found.");
  const vizIds = new Set(dashboard.layout.map((card) => card.visualizationId));
  const visualizations = workspace.visualizations.filter((viz) => vizIds.has(viz.id));
  const queryIds = new Set(visualizations.map((viz) => viz.queryId));
  const queries = workspace.queries.filter((query) => queryIds.has(query.id));
  return {
    format: "quackviz-dashboard",
    formatVersion: 1,
    exportedBy: { app: "QuackViz", appVersion: APP_VERSION, buildDate: BUILD_DATE, exportedAt: nowIso() },
    dashboard: deepClone(dashboard),
    visualizations: deepClone(visualizations),
    queries: deepClone(queries),
  };
}

export function importDashboardPackage(workspace, pkg) {
  if (!pkg || pkg.format !== "quackviz-dashboard") throw new Error("Unsupported dashboard package.");
  if (pkg.formatVersion > 1) throw new Error(`Unsupported future dashboard package version ${pkg.formatVersion}.`);
  const idMap = new Map();
  const mapId = (id, prefix) => {
    if (!idMap.has(id)) idMap.set(id, workspace.queries.some((q) => q.id === id) || workspace.visualizations.some((v) => v.id === id) || workspace.dashboards.some((d) => d.id === id) ? uid(prefix) : id);
    return idMap.get(id);
  };
  for (const query of pkg.queries || []) {
    const id = mapId(query.id, "query");
    if (!workspace.queries.some((item) => item.id === id)) workspace.queries.push({ ...deepClone(query), id });
  }
  for (const viz of pkg.visualizations || []) {
    const id = mapId(viz.id, "viz");
    const queryId = mapId(viz.queryId, "query");
    if (!workspace.visualizations.some((item) => item.id === id)) workspace.visualizations.push({ ...deepClone(viz), id, queryId, spec: { ...viz.spec, dataset: { queryId } } });
  }
  const dashboard = normalizeDashboard({
    ...pkg.dashboard,
    id: mapId(pkg.dashboard.id, "dashboard"),
    layout: (pkg.dashboard.layout || []).map((card) => ({ ...card, id: uid("card"), visualizationId: mapId(card.visualizationId, "viz") })),
  });
  workspace.dashboards.push(dashboard);
  workspace.active.dashboardId = dashboard.id;
  workspace.updatedAt = nowIso();
  return { dashboard, importedQueries: (pkg.queries || []).length, importedVisualizations: (pkg.visualizations || []).length };
}

export function createSnapshotHtml({ dashboard, cardStates = {}, includeSql = false }) {
  const cards = dashboard.layout.map((card) => {
    const state = cardStates[card.id] || {};
    const title = state.visualization?.name || card.titleOverride || "Dashboard card";
    const sql = includeSql && state.query?.sql ? `<pre>${escapeHtml(state.query.sql)}</pre>` : "";
    return `<section><h2>${escapeHtml(title)}</h2><p>Status: ${escapeHtml(state.status || "not refreshed")} · Rows: ${escapeHtml(state.rowCount ?? "-")} · Runtime: ${escapeHtml(state.runtimeMs ?? "-")} ms</p>${sql}</section>`;
  }).join("\n");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(dashboard.name)} snapshot</title><style>body{font-family:system-ui;margin:24px}section{border:1px solid #ccc;padding:12px;margin:12px 0}</style></head><body><h1>${escapeHtml(dashboard.name)}</h1><p>Snapshot generated by QuackViz ${APP_VERSION} (${BUILD_DATE}) at ${escapeHtml(nowIso())}.</p>${cards}</body></html>`;
}

function escapeHtml(value) {
  return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
